appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XijTPNgMpA+gikbJpSkdanXhH5yl/jHicqakGQ2IdipkVMADbB2pbwz9aOiYBxHGVakYZj7jb0v5Uzw/WsgzQiJfFYn4FGno+79g9yyB/8r4sJjGBoEw1X4SKRj9B3YtJVDIcouIfGAuUjhbECri6XqqCv+IJa/LKf7R2LWRPtIiv98rNcHgkZOKDPpCa6/QVgE1YMxCEdhir4GVlU7Sr3uLqRRs2Lone9Aj5m4b5MzKTiOZmqj94r6twq1FpeWE6/yEgrli+nzC+hX9Lmh5Gae66GsEijDRrD4Xe7GAAXCCbdo8e14oO2rw5yYgbAa+OHhpcVxdtF/5XXKPqZQ4jvBYm0v9DCi1VREuVkv7NMU6Ox1cMIm2pChD3H0szMtReBKRmQHkmXcMrtowMlHp7bV0ZFCS13IcBYjvGPPfhfTWI689XFa7Un3rPEPnWH30D3Q9dnmi4g9dFV2orFXVeSkeKpmsG4gyYQl47ICDbPjZVm9/3jb8vE3dsqhi++0oYIlaYm4sqU9hoqh2xuMeJiDEwungLqFLKdsP4MoGJKJVVAj/MlojHiI3L1mvakoBLvBVYlXxVKzrXUOwc6hO7AOYegw6nTrd9oGRjpTLUqmpNYkNdPp8HR85dQUYndkSR66OUy6Jipkq+dJqYpnuEsl1MsLhd4baX6qXC0YlEv0=}
bot:
  automerge: true
